import "./globals.css";
import { Almarai } from "next/font/google";
import ClientComponent from "../components/ClientComponent";

const almarai = Almarai({
  weight: "400",
  subsets: ["arabic"],
  variable: "--display-font",
});
export const metadata = {
  title: "اطلب اونلاين - الرفاعي",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="ar">
      <ClientComponent>
        <body dir="rtl" className={almarai.variable}>
          {children}
        </body>
      </ClientComponent>
    </html>
  );
};
export default RootLayout;
