import "./globals.css";
import type { Metadata } from "next";
import { Almarai } from "next/font/google";

const almarai = Almarai({
  weight: "400",
  subsets: ["arabic"],
  variable: "--display-font",
});
export const metadata: Metadata = {
  title: "AL-Refai Roastery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //sagy
  return (
    <html lang="en">
      <body className={almarai.variable}>{children}</body>
    </html>
  );
}
