import "./globals.css";
import { Almarai } from "next/font/google";
import { Provider } from "react-redux";
import store from "./rtk/store";
const almarai = Almarai({
  weight: "400",
  subsets: ["arabic"],
  variable: "--display-font",
});
export const metadata = {
  title: "Refai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={almarai.variable}>{children}</body>
      </Provider>
    </html>
  );
}
